language: node_js
node_js:
 - 13
services:
 - docker
install:
 - echo "nothing to install"
before_script:
 - echo "nothing to run before script"
script:
 - docker build . -t simple-node-image
 - docker tag simple-node-image $DOCKER_USERNAME/simple-node-image:latest
after_success:
 - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
 - docker push $DOCKER_USERNAME/simple-node-image

